### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Exited with code 3

### ISSUE THREAD

**Issue by eduardocruz** [jadjoubran/webdash#93]
Just installed, and when I tried to run I got the message below.

node version: 6.8.0

```
Webdash running on http://localhost:3456!
(node:25651) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/vagrant/Code/platform/node_modules/webdash/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
(node:25651) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25651) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jadjoubran** [comment]
Hey @eduardocruz 
Apologies for the late reply
As mentioned in the [Readme](https://github.com/jadjoubran/webdash#documentation), this package requires Node > 8
